Repository jhipster/jhipster-online, pull requests merged in 2020-08, with the labels that each got.

#214 Fix some Remaining Vulnerabilities and Code Smells
  src/main/java/io/github/jhipster/online/security/jwt/TokenProvider.java
  src/main/java/io/github/jhipster/online/service/GithubService.java
  src/main/java/io/github/jhipster/online/service/GitlabService.java
  src/main/java/io/github/jhipster/online/service/JHipsterService.java
  src/main/java/io/github/jhipster/online/service/JdlMetadataService.java
  src/main/java/io/github/jhipster/online/service/JdlService.java
  src/main/java/io/github/jhipster/online/service/UserService.java
  src/main/java/io/github/jhipster/online/service/interfaces/GitProviderService.java
  src/main/java/io/github/jhipster/online/web/rest/CiCdResource.java
  src/main/java/io/github/jhipster/online/web/rest/GeneratorResource.java
  src/main/java/io/github/jhipster/online/web/rest/GitResource.java
  src/main/java/io/github/jhipster/online/web/rest/JdlResource.java
  src/main/java/io/github/jhipster/online/web/rest/StatisticsResource.java
  src/main/java/io/github/jhipster/online/web/rest/UserJWTController.java
  src/test/java/io/github/jhipster/online/config/WebConfigurerTest.java
  src/test/java/io/github/jhipster/online/repository/CustomAuditEventRepositoryIT.java
  src/test/java/io/github/jhipster/online/security/jwt/JWTFilterTest.java
  src/test/java/io/github/jhipster/online/security/jwt/TokenProviderTest.java
  src/test/java/io/github/jhipster/online/service/MailServiceIT.java
  src/test/java/io/github/jhipster/online/service/enums/TemporalValueTypeTest.java
  src/test/java/io/github/jhipster/online/web/rest/AccountResourceIT.java
Labels: $$ bug-bounty $$, $100, Status: Review Needed :pray:

#222 Change ROLE for getAllUsers API
  src/main/java/io/github/jhipster/online/web/rest/UserResource.java
  src/test/java/io/github/jhipster/online/web/rest/UserResourceIT.java
Labels: Status: Completed :tada:, Type: Enhancement :rocket:

#174 Add Auto Deployments with CloudRun + GitHub Actions
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  README.md
  app.yaml
  pom.xml
  src/main/resources/config/application-gcp.yml
  src/main/resources/config/application-prod.yml
Labels: Status: Review Needed :pray:
